version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"

  cors-proxy:
    build:
      context: ./cors-proxy
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
